# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-13 22:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('city', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=45)),
                ('last_name', models.CharField(max_length=45)),
                ('address', models.TextField(null=True)),
                ('zip_code', models.CharField(max_length=45, null=True)),
                ('city_name', models.CharField(max_length=45, null=True)),
                ('country', models.CharField(max_length=45, null=True)),
                ('phone', models.CharField(max_length=45, null=True)),
                ('birth_date', models.DateField(null=True)),
                ('contract_start_date', models.DateField(verbose_name='Start contract date')),
                ('contract_end_date', models.DateField(null=True, verbose_name='End contract date')),
                ('contract_type', models.CharField(max_length=45)),
                ('id_type', models.CharField(max_length=45, verbose_name='ID card type')),
                ('id_start_date', models.DateField(null=True, verbose_name='ID card start date')),
                ('id_end_date', models.DateField(null=True, verbose_name='ID card due date')),
                ('citizenship', models.CharField(max_length=45)),
                ('email', models.CharField(max_length=100, null=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='city.City')),
            ],
        ),
    ]
