# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-13 23:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='public_day_day_hours',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='public_day_night_hours',
        ),
        migrations.AddField(
            model_name='schedule',
            name='public_holiday_day_hours',
            field=models.TimeField(null=True, verbose_name='Public holiday: Number of hours worked as day hours'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='public_holiday_night_hours',
            field=models.TimeField(null=True, verbose_name='Public holiday: Number of hours worked as night hours'),
        ),
    ]
